# Generated by Django 2.2.6 on 2022-09-14 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradasaida', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='receita',
            new_name='receita_despesa',
        ),
    ]
