# Generated by Django 2.2.6 on 2022-10-31 01:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entradasaida', '0002_auto_20220914_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleFinanceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=200, null=True)),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=100)),
                ('data_registro', models.DateField(blank=True, default=datetime.datetime.now)),
                ('receita_despesa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entradasaida.Receita')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
